name: Atualizar Troféus do GitHub

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# ISSO AQUI RESOLVE O ERRO 128: Dá permissão para o robô salvar a imagem
permissions:
  contents: write 

jobs:
  update-trophies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4 # Atualizado para v4 para tirar o aviso amarelo
        
      - name: Baixar SVG dos Troféus
        run: curl -s "https://github-profile-trophy.vercel.app/api?username=motajoao1&theme=radical&no-frame=true&margin-w=15" -o trophies.svg
        
      - name: Fazer o Commit e Push da imagem
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add trophies.svg
          git commit -m "Atualizando troféus do perfil" || exit 0
          git push
